import React, { useState } from "react";
import { Bot, UserCheck, ChevronRight } from "lucide-react";
import FileOutputIcon from "./ui/FileOutputIcon";
import UserRoundCheckIcon from "./ui/UserRoundCheckIcon";
import MessageSquareTextIcon from "./ui/MessageSquareTextIcon";
import SearchBar from "./SearchBar";
import FilterBottomSheet from "./FilterBottomSheet";
import TabToggle from "./common/TabToggle";
import ScreenHeader from "./common/ScreenHeader";
import type { ApprovalData } from "./ApprovalDetailsScreen";

interface ApprovalsScreenProps {
  onNavigate: (
    screen:
      | "signin"
      | "verify"
      | "terms"
      | "privacy"
      | "home"
      | "agents"
      | "agent-details"
      | "outputs"
      | "approvals"
      | "approval-details"
      | "transcript"
      | "output-details"
      | "notifications",
    data?: any,
  ) => void;
  isKeyboardOpen: boolean;
}

const approvals: Array<{
  title: string;
  subtitle: string;
  time: string;
  isUrgent: boolean;
  detailData: ApprovalData;
}> = [
  // Item 1 → Text input screen
  {
    title: "Review AI-generated customer emails before sending",
    subtitle: "Hr department",
    time: "10:32 AM",
    isUrgent: false,
    detailData: {
      type: "text" as const,
      title: "Review AI-generated customer emails before sending",
      description:
        "Please review the emails generated by the AI agent for customers, it will be automatically sent after you approve these emails.",
      textInputPlaceholder: "Type here",
      textInputMaxLength: 500,
      jobDescription:
        "Please review the emails generated by the AI agent for customers, it will be automatically sent after you approve these emails. These ag...",
      isUrgent: false,
      agentName: "Revenue services",
      agentTask: "Leads qualification",
    },
  },

  // Item 2 → Grouped multi-select screen
  {
    title: "Grant access to confidential customer records",
    subtitle: "Hr operations",
    time: "10:32 AM",
    isUrgent: true,
    detailData: {
      type: "select" as const,
      title: "Grant access to confidential customer records",
      description:
        "Please review the request to grant access to confidential customer records...",
      optionGroups: [
        {
          heading: "Choose options heading 1",
          selectionType: "multiple" as const,
          options: [
            { id: "g1_opt_1", label: "Option 1" },
            { id: "g1_opt_2", label: "Option 2" },
            { id: "g1_opt_3", label: "Option 3" },
            { id: "g1_opt_4", label: "Option 4" },
          ],
        },
        {
          heading: "Choose options heading 2",
          selectionType: "multiple" as const,
          options: [
            { id: "g2_opt_1", label: "Option 1" },
            { id: "g2_opt_2", label: "Option 2" },
            { id: "g2_opt_3", label: "Option 3" },
            { id: "g2_opt_4", label: "Option 4" },
          ],
        },
      ],
      jobDescription:
        "Please review the request to grant access. This action will be logged and audited.",
      isUrgent: true,
      agentName: "Security services",
      agentTask: "Access management",
    },
  },

  // Item 3 → Info-only screen (Got It button)
  {
    title: "Review API calls that trigger financial transactions",
    subtitle: "Hr operations",
    time: "10:32 AM",
    isUrgent: false,
    detailData: {
      type: "info" as const,
      title: "Review API calls that trigger financial transactions",
      description:
        "Please review the API calls that trigger financial transactions before approval.",
      jobDescription:
        "Review the API calls that trigger financial transactions.",
      isUrgent: false,
      agentName: "Finance services",
      agentTask: "Transaction management",
    },
  },

  // Item 4 → Single select with "Others" requiring text input
  {
    title: "Approve documents sent outside the organization",
    subtitle: "Hr operations",
    time: "10:32 AM",
    isUrgent: false,
    detailData: {
      type: "select" as const,
      title: "Approve documents sent outside the organization",
      description:
        "Please review the documents being sent outside the organization.",
      selectionType: "single" as const,
      options: [
        { id: "opt_1", label: "Option 1" },
        { id: "opt_2", label: "Option 2" },
        { id: "opt_3", label: "Option 3" },
        { id: "other", label: "Others", requiresInput: true },
      ],
      jobDescription: "Approve documents sent outside the organization.",
      isUrgent: false,
      agentName: "Compliance services",
      agentTask: "Document review",
    },
  },

  // Item 5 → Standard multi-select screen
  {
    title: "Review AI-generated customer emails before sending",
    subtitle: "Hr operations",
    time: "10:32 AM",
    isUrgent: true,
    detailData: {
      type: "select" as const,
      title: "Review AI-generated customer emails before sending",
      description:
        "Please review the emails generated by the AI agent for customers.",
      selectionType: "multiple" as const,
      options: [
        { id: "opt_1", label: "Option 1" },
        { id: "opt_2", label: "Option 2" },
        { id: "opt_3", label: "Option 3" },
        { id: "opt_4", label: "Option 4" },
      ],
      jobDescription:
        "Please review the emails generated by the AI agent.",
      isUrgent: true,
      agentName: "Revenue services",
      agentTask: "Leads qualification",
    },
  },
];

const ApprovalsScreen: React.FC<ApprovalsScreenProps> = ({ onNavigate, isKeyboardOpen }) => {
  const [activeTab, setActiveTab] = useState<"all" | "urgent">("all");
  const [isSearchActive, setIsSearchActive] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");
  const [isFilterOpen, setIsFilterOpen] = useState(false);

  const allCount = approvals.length;
  const urgentCount = approvals.filter((a) => a.isUrgent).length;

  const filteredApprovals = approvals.filter((approval) => {
    const matchesTab = activeTab === "all" || approval.isUrgent;
    const query = searchQuery.toLowerCase();
    const matchesSearch =
      approval.title.toLowerCase().includes(query) ||
      approval.subtitle.toLowerCase().includes(query);
    return matchesTab && matchesSearch;
  });

  return (
    <div className="w-full h-[100dvh] flex flex-col bg-[var(--background)] overflow-hidden">

      {/* ── Header ── */}
      <header className="flex-shrink-0 px-[var(--spacing-16)] pt-[max(var(--safe-top),2.75rem)] pb-3">
        {!isSearchActive ? (
          <ScreenHeader
            title="Approvals"
            onSearchClick={() => setIsSearchActive(true)}
            onNotificationsClick={() => onNavigate("notifications")}
          />
        ) : (
          <SearchBar
            searchQuery={searchQuery}
            setSearchQuery={setSearchQuery}
            setIsSearchActive={setIsSearchActive}
            placeholder="Search approvals..."
            onFilterClick={() => setIsFilterOpen(true)}
          />
        )}
      </header>

      {/* ── Tab Toggle ── */}
      <div className="flex-shrink-0 flex justify-center px-[var(--spacing-16)] py-2">
        <TabToggle
          tabs={[
            { label: `All (${allCount})`, value: "all" },
            { label: `Urgent (${urgentCount})`, value: "urgent" },
          ]}
          activeTab={activeTab}
          onTabChange={(value) => setActiveTab(value as "all" | "urgent")}
        />
      </div>

      {/* ── Approvals List ── */}
      <div className="flex-1 overflow-y-auto px-[var(--spacing-16)] pb-[calc(4rem+max(var(--safe-bottom),1.25rem))] min-h-0">
        {filteredApprovals.length === 0 ? (
          <div className="flex flex-col items-center justify-center h-full">
            <p className="text-sm text-[var(--muted-foreground)]">
              No approvals found
            </p>
          </div>
        ) : (
          <div className="flex flex-col gap-[var(--spacing-16)]">
            {filteredApprovals.map((approval, index) => (
              <button
                key={`${approval.title}-${index}`}
                type="button"
                onClick={() => onNavigate("approval-details", approval.detailData)}
                className="w-full flex flex-row items-start gap-3 sm:gap-4 border-b cursor-pointer text-left active:bg-[var(--grey-50)] transition-colors"
                style={{ borderColor: "var(--grey-100)" }}
              >
                {/* Avatar icon */}
                <div className="w-8 h-8 flex-shrink-0 rounded-full bg-[var(--grey-200)] flex items-center justify-center mt-0.5">
                  <UserCheck className="w-4 h-4 text-[var(--grey-700)]" />
                </div>

                {/* Text content */}
                <div className="flex-1 flex flex-col gap-0.5 min-w-0">
                  <div className="flex items-start gap-2">
                    <p className="flex-1 text-sm font-medium line-clamp-2 text-[var(--grey-1000)] leading-snug">
                      {approval.title}
                    </p>
                    {approval.isUrgent && (
                      <span className="flex-shrink-0 text-[0.625rem] font-semibold px-1.5 py-0.5 rounded bg-[var(--error-200)] text-[var(--error-600)]">
                        Urgent
                      </span>
                    )}
                  </div>
                  <p className="text-xs font-medium text-[var(--grey-700)]">
                    {approval.subtitle}
                  </p>
                  <span className="text-xs text-[var(--grey-500)] mt-1">
                    {approval.time}
                  </span>
                </div>

                {/* Chevron */}
                <ChevronRight
                  size={20}
                  className="flex-shrink-0 mt-0.5"
                  style={{ color: "var(--muted-foreground)" }}
                />
              </button>
            ))}
          </div>
        )}
      </div>

      {/* ── Filter Bottom Sheet ── */}
      <FilterBottomSheet
        isOpen={isFilterOpen}
        onClose={() => setIsFilterOpen(false)}
        onApply={() => setIsFilterOpen(false)}
      />

      {/* ── Bottom Navigation ── */}
      <nav className={`fixed bottom-0 left-0 w-full bg-white border-t border-[var(--grey-200)] z-40 flex px-[0.75rem] gap-[0.75rem] pt-[0.75rem] pb-[max(var(--safe-bottom),0.75rem)] transition-transform duration-200 ${isKeyboardOpen ? 'translate-y-full opacity-0 pointer-events-none' : 'translate-y-0 opacity-100'}`}>
        <button
          onClick={() => onNavigate('home')}
          className="flex-1 h-[2.75rem] flex flex-col items-center justify-between relative touch-manipulation group"
        >
          <div className="w-6 h-6 flex items-center justify-center">
            <MessageSquareTextIcon size={24} style={{ color: 'var(--grey-500)' }} />
          </div>
          <span className="text-[0.625rem] leading-[0.75rem] font-medium text-[var(--grey-500)]">Chat</span>
        </button>

        <button
          onClick={() => onNavigate('agents')}
          className="flex-1 h-[2.75rem] flex flex-col items-center justify-between relative touch-manipulation group"
        >
          <div className="w-6 h-6 flex items-center justify-center">
            <Bot size={24} strokeWidth={1.5} style={{ color: 'var(--grey-500)' }} />
          </div>
          <span className="text-[0.625rem] leading-[0.75rem] font-medium text-[var(--grey-500)]">Agent</span>
        </button>

        <button
          onClick={() => onNavigate('outputs')}
          className="flex-1 h-[2.75rem] flex flex-col items-center justify-between relative touch-manipulation group"
        >
          <div className="w-6 h-6 flex items-center justify-center">
            <FileOutputIcon size={24} style={{ color: 'var(--grey-500)' }} />
          </div>
          <span className="text-[0.625rem] leading-[0.75rem] font-medium text-[var(--grey-500)]">Outputs</span>
        </button>

        <button
          onClick={() => onNavigate('approvals')}
          className="flex-1 h-[2.75rem] flex flex-col items-center justify-between relative touch-manipulation group"
        >
          {true && (
            <div className="absolute top-[-0.75rem] left-0 w-full h-[0.125rem] bg-[var(--purple-1000)] rounded-b-sm" />
          )}
          <div className="w-6 h-6 flex items-center justify-center">
            <UserRoundCheckIcon size={24} style={{ color: 'var(--purple-1000)' }} />
          </div>
          <span className="text-[0.625rem] leading-[0.75rem] font-medium text-[var(--purple-1000)]">Approvals</span>
        </button>
      </nav>
    </div>
  );
};

export default ApprovalsScreen;