import React, { useState } from "react";
import { ArrowLeft, ChevronRight } from "lucide-react";

interface ApprovalDetailsScreenProps {
  onNavigate: (screen: "splash" | "signin" | "verify" | "terms" | "privacy" | "home" | "agents" | "outputs" | "approvals" | "approval-details" | "agent-details") => void;
}

const fullDescription = "Please review the emails generated by the AI agent for customers, it will be automatically sent after you approve these emails. These agents are built by the email sender agent which has been configured to send out weekly subscription reminders, account verification instructions and service outage notifications to our customer base.";

const ApprovalDetailsScreen: React.FC<ApprovalDetailsScreenProps> = ({ onNavigate }) => {
  const [isDescExpanded, setIsDescExpanded] = useState(false);
  const truncatedLength = 150;
  const truncatedDescription = fullDescription.substring(0, truncatedLength);
  const isTruncated = fullDescription.length > truncatedLength;
  return (
    <div
      className="w-full h-full flex flex-col justify-between bg-[var(--background)]"
      style={{
        paddingTop: "max(env(safe-area-inset-top), 24px)",
        paddingBottom: "max(env(safe-area-inset-bottom), 24px)",
      }}
    >
      <header className="px-6 py-4 flex flex-row items-center gap-4 flex-shrink-0">
        <button
          type="button"
          onClick={() => onNavigate('approvals')}
          className="cursor-pointer"
          style={{ color: "var(--foreground)" }}
        >
          <ArrowLeft size={20} />
        </button>
        <h1 className="text-xl font-bold" style={{ color: "var(--foreground)" }}>
          Approvals
        </h1>
      </header>

      <div className="flex-grow overflow-y-auto px-6 mt-2">
        <div className="mb-4">
          <h2 className="text-lg font-bold" style={{ color: "var(--foreground)" }}>
            Review AI-generated customer emails before sending
          </h2>
        </div>

        <section className="border-b border-[var(--grey-200)] pb-4 mb-4">
          <h3 className="text-sm font-semibold mb-1" style={{ color: "var(--foreground)" }}>
            Description
          </h3>
          <div className="text-sm text-[var(--grey-700)] leading-relaxed">
            {isDescExpanded ? fullDescription : truncatedDescription}
            {isTruncated && (
              <button
                onClick={(e) => { e.stopPropagation(); setIsDescExpanded(!isDescExpanded); }}
                className="text-[var(--purple-1000)] font-medium ml-1 cursor-pointer"
              >
                {isDescExpanded ? 'View less' : 'View more'}
              </button>
            )}
          </div>
        </section>

        <section className="mb-4">
          <h3 className="text-sm font-semibold mb-3" style={{ color: "var(--foreground)" }}>
            Emails to be sent
          </h3>

          <div className="border-b border-[var(--grey-200)] pb-4 mb-4">
            <p className="text-xs font-medium" style={{ color: "var(--foreground)" }}>
              Subscription renewal reminder
            </p>
            <p className="text-xs" style={{ color: "var(--muted-foreground)" }}>
              To : Ben.kolf@gmail.com
            </p>
          </div>

          <div className="border-b border-[var(--grey-200)] pb-4 mb-4">
            <p className="text-xs font-medium" style={{ color: "var(--foreground)" }}>
              Account verification instructions and guidance
            </p>
            <p className="text-xs" style={{ color: "var(--muted-foreground)" }}>
              To : Ben.kolf@gmail.com
            </p>
          </div>

          <div className="pb-4 border-b border-[var(--grey-200)]">
            <p className="text-xs font-medium" style={{ color: "var(--foreground)" }}>
              Service outage notification and alert
            </p>
            <p className="text-xs" style={{ color: "var(--muted-foreground)" }}>
              To : Ben.kolf@gmail.com
            </p>
          </div>
        </section>

        <section>
          <h3 className="text-sm font-semibold mb-3" style={{ color: "var(--foreground)" }}>
            Agents details
          </h3>
          <div
            className="flex flex-row items-center justify-between py-2 cursor-pointer transition-opacity hover:opacity-80 active:scale-[0.99]"
            onClick={() => onNavigate('agent-details')}
          >
            <div className="flex flex-row items-center gap-3">
              <div className="w-[40px] h-[40px] rounded-full bg-[var(--grey-200)] flex items-center justify-center text-[var(--foreground)] font-semibold text-xs">
                ES
              </div>
              <div>
                <p className="text-sm font-semibold" style={{ color: "var(--foreground)" }}>
                  Email services
                </p>
                <p className="text-xs" style={{ color: "var(--muted-foreground)" }}>
                  Generates and sends emails
                </p>
              </div>
            </div>
            <div className="text-[var(--muted-foreground)]">
              <ChevronRight size={20} />
            </div>
          </div>
        </section>
      </div>

      <div className="p-4 flex flex-row gap-3 justify-center items-center w-full border-t border-[var(--grey-200)] pt-4 flex-shrink-0">
        <button
          type="button"
          onClick={() => onNavigate('approvals')}
          className="w-[163.5px] h-[40px] rounded-xl flex items-center justify-center text-sm font-semibold cursor-pointer transition-all border border-[var(--purple-1000)] text-[var(--purple-1000)] bg-transparent hover:bg-[var(--grey-100)]"
        >
          Reject
        </button>
        <button
          type="button"
          onClick={() => onNavigate('approvals')}
          className="w-[163.5px] h-[40px] rounded-xl flex items-center justify-center text-sm font-semibold cursor-pointer transition-all bg-[var(--purple-1000)] text-white shadow-sm hover:opacity-90"
        >
          Approve
        </button>
      </div>
    </div>
  );
};

export default ApprovalDetailsScreen;
