import { useState } from "react";

// ── Dynamic Data Interfaces ──
export interface ApprovalOption {
  id: string | number;
  label: string;
  requiresInput?: boolean;
}

export interface ApprovalData {
  title: string;
  description: string;
  selectionType?: "single" | "multiple";
  options: ApprovalOption[];
  jobDescription: string;
  isUrgent?: boolean;
  agentName: string;
  agentTask: string;
}

interface ApprovalDetailsScreenProps {
  onNavigate: (screen: string, data?: Record<string, unknown>) => void;
  approvalData?: ApprovalData;
}

const defaultApprovalData: ApprovalData = {
  title: "Review AI-generated customer emails before sending",
  description: "Please review the emails generated by the AI agent for customers, it will be automatically sent after you approve these emails.",
  selectionType: "multiple",
  options: [
    { id: "opt_1", label: "Option 1" },
    { id: "opt_2", label: "Option 2" },
    { id: "opt_3", label: "Option 3" },
    { id: "opt_4", label: "Option 4" },
  ],
  jobDescription: "Please review the emails generated by the AI agent for customers, it will be automatically sent after you approve these emails.",
  isUrgent: true,
  agentName: "Revenue services",
  agentTask: "Leads qualification",
};

export default function ApprovalDetailsScreen({
  onNavigate,
  approvalData = defaultApprovalData,
}: ApprovalDetailsScreenProps) {
  const isSingle = approvalData.selectionType === "single";

  const [selectedMultiple, setSelectedMultiple] = useState<Array<string | number>>([]);
  const [selectedSingle, setSelectedSingle] = useState<string | number | null>(null);
  const [customInput, setCustomInput] = useState("");
  const [showError, setShowError] = useState(false);

  const toggleOption = (id: string | number) => {
    setShowError(false);
    if (isSingle) {
      setSelectedSingle(id);
      if (!approvalData.options.find((o) => o.id === id)?.requiresInput) {
        setCustomInput("");
      }
    } else {
      setSelectedMultiple((prev) =>
        prev.includes(id) ? prev.filter((optId) => optId !== id) : [...prev, id]
      );
    }
  };

  const handleApprove = () => {
    const hasSelection = isSingle ? selectedSingle !== null : selectedMultiple.length > 0;

    if (!hasSelection) {
      setShowError(true);
      return;
    }

    const selectedOptionData = approvalData.options.find((o) => o.id === selectedSingle);
    if (isSingle && selectedOptionData?.requiresInput && customInput.trim() === "") {
      setShowError(true);
      return;
    }

    console.log("Approved:", {
      type: isSingle ? "single" : "multiple",
      selections: isSingle ? selectedSingle : selectedMultiple,
      customInput: customInput,
    });
    onNavigate("approvals");
  };

  return (
    <div className="flex flex-col w-full h-[100dvh] bg-[var(--grey-50)]">
      {/* Header */}
      <header className="sticky top-0 z-20 w-full bg-[var(--grey-50)] pt-[max(env(safe-area-inset-top),2.75rem)] pb-4 px-[var(--spacing-16)] flex items-center gap-4">
        <button onClick={() => onNavigate("approvals")} className="w-9 h-9 flex items-center justify-center active:bg-[var(--grey-200)] rounded-full transition-colors">
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M19 12H5M12 19l-7-7 7-7" /></svg>
        </button>
        <h1 className="font-semibold text-[1.25rem] text-[var(--grey-1000)]">Approvals</h1>
      </header>

      {/* Scrollable Body */}
      <main className="flex-1 overflow-y-auto px-[var(--spacing-16)] flex flex-col">
        {/* Agent Info */}
        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 bg-white border border-[var(--grey-200)] rounded-xl flex items-center justify-center shadow-sm">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-[var(--grey-600)]">
              <rect x="3" y="11" width="18" height="10" rx="2" /><circle cx="12" cy="5" r="2" /><path d="M12 7v4" /><line x1="8" y1="16" x2="8" y2="16" /><line x1="16" y1="16" x2="16" y2="16" />
            </svg>
          </div>
          <div className="flex flex-col">
            <span className="font-semibold text-sm text-[var(--grey-1000)]">{approvalData.agentName}</span>
            <span className="text-xs text-[var(--grey-500)]">{approvalData.agentTask}</span>
          </div>
        </div>

        {/* Main Approval Card */}
        <div className="bg-white border border-[var(--grey-200)] rounded-xl p-5 mb-4 shadow-sm flex flex-col">
          {approvalData.isUrgent && (
            <span className="bg-[var(--error-200)] text-[var(--error-600)] text-xs font-medium px-2 py-1 rounded-md w-fit mb-3">Urgent</span>
          )}
          <h2 className="font-semibold text-[1rem] leading-snug text-[var(--grey-1000)] mb-2">{approvalData.title}</h2>
          <p className="text-sm text-[var(--grey-600)] leading-relaxed mb-4 line-clamp-2">
            {approvalData.description}
            <button className="text-[var(--primary)] font-medium ml-1 underline">View more</button>
          </p>

          <div className="border-t border-[var(--grey-200)] pt-4">
            <h3 className="font-medium text-sm text-[var(--grey-1000)] mb-3">
              {isSingle ? "Choose an option" : "Choose options"}
            </h3>
            <div className="flex flex-col gap-3">
              {approvalData.options.map((option) => {
                const isSelected = isSingle
                  ? selectedSingle === option.id
                  : selectedMultiple.includes(option.id);
                return (
                  <div key={option.id} className="flex flex-col w-full">
                    <button
                      onClick={() => toggleOption(option.id)}
                      className="flex items-center gap-3 text-left touch-manipulation group w-full"
                    >
                      <div
                        className={`w-5 h-5 flex items-center justify-center shrink-0 transition-colors border ${
                          isSingle ? "rounded-full" : "rounded-[4px]"
                        } ${
                          isSelected
                            ? "bg-[var(--purple-1000)] border-[var(--purple-1000)]"
                            : "border-[var(--grey-400)] group-active:bg-[var(--grey-100)]"
                        }`}
                      >
                        {isSelected && !isSingle && (
                          <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
                            <polyline points="20 6 9 17 4 12" />
                          </svg>
                        )}
                        {isSelected && isSingle && (
                          <div className="w-2 h-2 bg-white rounded-full" />
                        )}
                      </div>
                      <span className="text-sm text-[var(--grey-800)]">{option.label}</span>
                    </button>

                    {isSelected && option.requiresInput && (
                      <div className="mt-3 w-full">
                        <textarea
                          value={customInput}
                          onChange={(e) => {
                            setShowError(false);
                            setCustomInput(e.target.value);
                          }}
                          maxLength={100}
                          placeholder="Type here"
                          className="w-full min-h-[4rem] bg-[var(--grey-50)] border border-[var(--grey-200)] rounded-lg p-3 text-sm text-[var(--grey-1000)] resize-none focus:outline-none focus:border-[var(--purple-1000)] transition-colors"
                        />
                        <div className="w-full text-right text-xs text-[var(--grey-400)] mt-1">
                          {customInput.length}/100
                        </div>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
            {showError && (
              <p className="text-[var(--error-600)] text-xs font-medium mt-4">
                Please select {isSingle ? "an" : "the"} option{!isSingle && "s"} to continue
              </p>
            )}
          </div>
        </div>

        {/* Job Details Card */}
        <div className="bg-white border border-[var(--grey-200)] rounded-xl p-5 mb-6 shadow-sm flex flex-col">
          <h3 className="font-semibold text-[1rem] text-[var(--grey-1000)] mb-2">Job</h3>
          <p className="text-sm text-[var(--grey-600)] leading-relaxed line-clamp-3">
            {approvalData.jobDescription}
            <button className="text-[var(--primary)] font-medium ml-1 underline">View more</button>
          </p>
        </div>
      </main>

      {/* Sticky Footer */}
      <footer className="w-full bg-white border-t border-[var(--grey-200)] px-[var(--spacing-16)] py-4 pb-[max(env(safe-area-inset-bottom),2.125rem)] flex gap-3 z-20">
        <button onClick={() => onNavigate("approvals")} className="flex-1 h-[3rem] rounded-xl border border-[var(--purple-1000)] text-[var(--purple-1000)] font-semibold text-sm flex items-center justify-center active:bg-[var(--purple-100)] transition-colors">Reject</button>
        <button onClick={handleApprove} className="flex-1 h-[3rem] rounded-xl bg-[var(--purple-1000)] text-white font-semibold text-sm flex items-center justify-center active:bg-[var(--purple-900)] transition-colors">Approve</button>
      </footer>
    </div>
  );
}

